#256 refactor : 기존 코드 리팩토링
Leets-Official/Weeth-FE pull request #260
Opened 2024-11-16 18:15 UTC by JIN921

## 1. 무슨 이유로 코드를 변경했나요?
기존 코드에서 리팩토링할 부분을 변경했습니다.

## 2. 완료 사항

- 드롭다운 통합
-> 회원가입과 마이페이지에서 따로 사용되던 드롭다운을 조건부 스타일링 받는 1개의 컴포넌트로 통합했습니다.

- 갈 곳 없는 파일들을 정리해 줬습니다.

- 영수증 메모 글자수 별로 다르게 스타일링 넣어서 글자가 이상하게 넘어가지 않도록 했습니다.
-> 기존
![image](https://github.com/user-attachments/assets/b06b6760-5435-4ae4-aa0a-2d3bd04444a0)

-> 변경 후
![image](https://github.com/user-attachments/assets/addb4eef-2ed9-4511-9044-598392cb515b)

## 3. 추가 사항

저희 원래 커밋 메세지 [feat] 어쩌구 이런식이엇는데 이제 feat: 어쩌구 이런식으로 바꾸나요? 예진이가 한 거 보니까 그렇게 햇길래 저도 오늘 커밋은 후자의 방식으로 햇어염

2024-11-16 19:18 UTC, yezzan9 commented
커밋메세지는 실수입니다....🥹 멍청이슈..

2024-11-16 19:36 UTC, yezzan9 requested changes

2024-11-16 19:36 UTC, yezzan9 commented on src/components/Modal/AdminEditDelModal.tsx
`AdminEditDelModal`을 삭제하고 해당 컴포넌트가 사용된 부분을 `EditDelModal`로 대체해주실 수 있을까요?
해당 파일이 `EditDelModal` 재사용을 안 하고 복붙해서 새로 만들어진 컴포넌트(?????)이기 때문입니다......^_ㅠ
-> 불필요한 분리라는 뜻!!

스타일 설정이 살짝 다를텐데,, 어차피 `ModalBackground` 스타일이 안 먹어서 모달을 불러오는 쪽에서 `overaly` 스타일을 적용해야하거든욧
-> 이 부분을 정리한 게 `EditDelModal`입니다😂

2024-11-16 19:36 UTC, yezzan9 commented on src/pages/Edit.tsx
> +// }
요거 주석처리 말고 그냥 지워도 될 것 같아욤

2024-11-17 17:11 UTC, yezzan9 commented
해당 부분 수정이 누락된 것 같아요!!
<img width="763" alt="스크린샷 2024-11-18 오전 2 11 26" src="https://github.com/user-attachments/assets/2a7e2cfd-b70f-4fbf-bda7-a327a0571771">

2024-11-18 02:03 UTC, JIN921 commented on src/components/Modal/AdminEditDelModal.tsx
아하 알겟습니당!

2024-11-18 02:03 UTC, JIN921 commented on src/pages/Edit.tsx
> +// }
넹!

2024-11-18 02:04 UTC, JIN921 commented
> 해당 부분 수정이 누락된 것 같아요!! <img alt="스크린샷 2024-11-18 오전 2 11 26" width="763" src="https://private-user-images.githubusercontent.com/92977621/386981862-2a7e2cfd-b70f-4fbf-bda7-a327a0571771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTU2ODUsIm5iZiI6MTczMTg5NTM4NSwicGF0aCI6Ii85Mjk3NzYyMS8zODY5ODE4NjItMmE3ZTJjZmQtYjcwZi00ZmJmLWJkYTctYTMyN2EwNTcxNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAyMDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NmNlM2Q4Y2MzNWU4ODQ4OWVmY2Q2Yzc3MDdjZmZlMmYzOTY2OTM1YmVjYzE3OWYwOWJmYzUwODAyMmVmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IWCbTB33cqKkm3T8cbovbPa81jOhfFwJxldKt7MH7Rg">

...... 아래에 잇어서 못 봣군요.. 다시 수정해서 push 할게여!

2024-11-18 06:11 UTC, yezzan9 approved these changes

2024-11-18 07:07 UTC, merged